proxies:
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.114.114.69:7306-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.114.114.69
    password: FoOiGlkAA9yPEGP
    port: 7306
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.68.134.196:808-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.68.134.196
    password: G!yBwPWH3Vao
    port: 808
    cipher: chacha20-ietf-poly1305
  - name: "\U0001F1FA\U0001F1F8:美国-ss-162.251.61.221:804-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 162.251.61.221
    password: G!yBwPWH3Vao
    port: 804
    cipher: chacha20-ietf-poly1305
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.68.134.37:2375-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.68.134.37
    password: faBAoD54k87UJG7
    port: 2375
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.114.114.69:5001-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.114.114.69
    password: Y6R9pAtvxxzmGC
    port: 5001
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.114.114.69:8091-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.114.114.69
    password: PCnnH6SQSnfoS27
    port: 8091
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.114.114.68:7307-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.114.114.68
    password: FoOiGlkAA9yPEGP
    port: 7307
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.68.134.37:5601-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.68.134.37
    password: Y6R9pAtvxxzmGC
    port: 5601
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.114.114.69:8008-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.114.114.69
    password: XKFKl2rULjIp74
    port: 8008
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-167.88.63.99:7307-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 167.88.63.99
    password: FoOiGlkAA9yPEGP
    port: 7307
    cipher: aes-256-gcm
  - name: "\U0001F1EF\U0001F1F5:日本-ss-45.66.134.176:807-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧"
    type: ss
    server: 45.66.134.176
    password: G!yBwPWH3Vao
    port: 807
    cipher: chacha20-ietf-poly1305
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.68.134.37:2376-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.68.134.37
    password: faBAoD54k87UJG7
    port: 2376
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.114.114.68:8091-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.114.114.68
    password: PCnnH6SQSnfoS27
    port: 8091
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.114.114.68:5004-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.114.114.68
    password: g5MeD6Ft3CWlJId
    port: 5004
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.68.135.208:8080-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.68.135.208
    password: KixLvKzwjekG00rm
    port: 8080
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.114.114.69:9101-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.114.114.69
    password: e4FCWrgpkji3QY
    port: 9101
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.114.114.69:5003-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.114.114.69
    password: g5MeD6Ft3CWlJId
    port: 5003
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.114.114.69:8009-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.114.114.69
    password: XKFKl2rULjIp74
    port: 8009
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-167.88.63.99:7306-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 167.88.63.99
    password: FoOiGlkAA9yPEGP
    port: 7306
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-167.88.63.99:2375-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 167.88.63.99
    password: faBAoD54k87UJG7
    port: 2375
    cipher: aes-256-gcm
  - name: "\U0001F1EF\U0001F1F5:日本-ss-45.66.134.176:810-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧"
    type: ss
    server: 45.66.134.176
    password: G!yBwPWH3Vao
    port: 810
    cipher: chacha20-ietf-poly1305
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.114.114.68:443-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.114.114.68
    password: pKEW8JPByTVTLtM
    port: 443
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.114.114.69:4444-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.114.114.69
    password: pKEW8JPByTVTLtM
    port: 4444
    cipher: aes-256-gcm
  - name: "\U0001F1EF\U0001F1F5:日本-ss-45.66.134.176:811-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧"
    type: ss
    server: 45.66.134.176
    password: G!yBwPWH3Vao
    port: 811
    cipher: chacha20-ietf-poly1305
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.114.114.69:9102-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.114.114.69
    password: e4FCWrgpkji3QY
    port: 9102
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.114.114.69:5601-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.114.114.69
    password: Y6R9pAtvxxzmGC
    port: 5601
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.114.114.68:2376-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.114.114.68
    password: faBAoD54k87UJG7
    port: 2376
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.68.134.37:5003-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.68.134.37
    password: g5MeD6Ft3CWlJId
    port: 5003
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-162.251.61.221:802-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 162.251.61.221
    password: G!yBwPWH3Vao
    port: 802
    cipher: chacha20-ietf-poly1305
  - name: "\U0001F1FA\U0001F1F8:美国-ss-162.251.61.221:808-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 162.251.61.221
    password: G!yBwPWH3Vao
    port: 808
    cipher: chacha20-ietf-poly1305
  - name: "\U0001F1FA\U0001F1F8:美国-ss-162.251.61.221:805-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 162.251.61.221
    password: G!yBwPWH3Vao
    port: 805
    cipher: chacha20-ietf-poly1305
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.86.135.169:9101-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.86.135.169
    password: e4FCWrgpkji3QY
    port: 9101
    cipher: aes-256-gcm
  - name: "\U0001F1EF\U0001F1F5:日本-ss-45.66.134.176:806-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧"
    type: ss
    server: 45.66.134.176
    password: G!yBwPWH3Vao
    port: 806
    cipher: chacha20-ietf-poly1305
  - name: "\U0001F1EF\U0001F1F5:日本-ss-45.66.134.176:809-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧"
    type: ss
    server: 45.66.134.176
    password: G!yBwPWH3Vao
    port: 809
    cipher: chacha20-ietf-poly1305
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.68.134.37:7307-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.68.134.37
    password: FoOiGlkAA9yPEGP
    port: 7307
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-162.251.61.221:806-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 162.251.61.221
    password: G!yBwPWH3Vao
    port: 806
    cipher: chacha20-ietf-poly1305
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.68.134.196:810-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.68.134.196
    password: G!yBwPWH3Vao
    port: 810
    cipher: chacha20-ietf-poly1305
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.68.134.37:5004-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.68.134.37
    password: g5MeD6Ft3CWlJId
    port: 5004
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-162.251.61.221:803-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 162.251.61.221
    password: G!yBwPWH3Vao
    port: 803
    cipher: chacha20-ietf-poly1305
  - name: "\U0001F1EF\U0001F1F5:日本-ss-45.66.134.176:805-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧"
    type: ss
    server: 45.66.134.176
    password: G!yBwPWH3Vao
    port: 805
    cipher: chacha20-ietf-poly1305
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.114.114.68:7306-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.114.114.68
    password: FoOiGlkAA9yPEGP
    port: 7306
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.68.135.208:8009-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.68.135.208
    password: XKFKl2rULjIp74
    port: 8009
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.114.114.68:8090-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.114.114.68
    password: PCnnH6SQSnfoS27
    port: 8090
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.68.134.37:7306-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.68.134.37
    password: FoOiGlkAA9yPEGP
    port: 7306
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-162.251.61.221:800-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 162.251.61.221
    password: G!yBwPWH3Vao
    port: 800
    cipher: chacha20-ietf-poly1305
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.114.114.68:8080-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.114.114.68
    password: KixLvKzwjekG00rm
    port: 8080
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-167.88.63.99:2376-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 167.88.63.99
    password: faBAoD54k87UJG7
    port: 2376
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.68.135.208:3389-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.68.135.208
    password: Y6R9pAtvxxzmGC
    port: 3389
    cipher: aes-256-gcm
  - name: "\U0001F1EF\U0001F1F5:日本-ss-45.66.134.176:803-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧"
    type: ss
    server: 45.66.134.176
    password: G!yBwPWH3Vao
    port: 803
    cipher: chacha20-ietf-poly1305
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.68.134.37:8091-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.68.134.37
    password: PCnnH6SQSnfoS27
    port: 8091
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.68.134.37:3389-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.68.134.37
    password: Y6R9pAtvxxzmGC
    port: 3389
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.68.134.196:805-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.68.134.196
    password: G!yBwPWH3Vao
    port: 805
    cipher: chacha20-ietf-poly1305
  - name: "\U0001F1FA\U0001F1F8:美国-ss-167.88.63.117:8119-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 167.88.63.117
    password: cdBIDV42DCwnfIN
    port: 8119
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.114.114.68:5001-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.114.114.68
    password: Y6R9pAtvxxzmGC
    port: 5001
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.68.134.196:812-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.68.134.196
    password: G!yBwPWH3Vao
    port: 812
    cipher: chacha20-ietf-poly1305
  - name: "\U0001F1FA\U0001F1F8:美国-ss-167.88.63.99:8090-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 167.88.63.99
    password: PCnnH6SQSnfoS27
    port: 8090
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.68.134.37:8080-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.68.134.37
    password: KixLvKzwjekG00rm
    port: 8080
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-167.88.63.99:8091-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 167.88.63.99
    password: PCnnH6SQSnfoS27
    port: 8091
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.68.134.196:802-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.68.134.196
    password: G!yBwPWH3Vao
    port: 802
    cipher: chacha20-ietf-poly1305
  - name: "\U0001F1FA\U0001F1F8:美国-ss-162.251.61.221:809-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 162.251.61.221
    password: G!yBwPWH3Vao
    port: 809
    cipher: chacha20-ietf-poly1305
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.121.43.51:2376-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.121.43.51
    password: faBAoD54k87UJG7
    port: 2376
    cipher: aes-256-gcm
  - name: "\U0001F1EF\U0001F1F5:日本-ss-45.66.134.176:802-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧"
    type: ss
    server: 45.66.134.176
    password: G!yBwPWH3Vao
    port: 802
    cipher: chacha20-ietf-poly1305
  - name: "\U0001F1EF\U0001F1F5:日本-ss-45.66.134.176:801-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧"
    type: ss
    server: 45.66.134.176
    password: G!yBwPWH3Vao
    port: 801
    cipher: chacha20-ietf-poly1305
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.68.134.196:800-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.68.134.196
    password: G!yBwPWH3Vao
    port: 800
    cipher: chacha20-ietf-poly1305
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.68.135.208:2375-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.68.135.208
    password: faBAoD54k87UJG7
    port: 2375
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.114.114.68:5003-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.114.114.68
    password: g5MeD6Ft3CWlJId
    port: 5003
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.68.135.208:8118-被墙-直连-解锁美国地区NF非自制剧"
    type: ss
    server: 38.68.135.208
    password: cdBIDV42DCwnfIN
    port: 8118
    cipher: aes-256-gcm
  - name: "\U0001F1FA\U0001F1F8:美国-ss-38.68.134.135:809-被墙-中转:38.68.134.196-解锁美国地区NF非自制剧"
    type: ss
    server: 38.68.134.135
    password: G!yBwPWH3Vao
    port: 809
    cipher: chacha20-ietf-poly1305
